# Generated by Django 3.1.7 on 2021-03-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210311_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
